package com.example.administrator.koudaiwanzi.home.entity.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HISTORY_ENTITY".
 */
public class HistoryEntity {

    private Long id;
    private String content;
    private String url;

    public HistoryEntity() {
    }

    public HistoryEntity(Long id) {
        this.id = id;
    }

    public HistoryEntity(Long id, String content, String url) {
        this.id = id;
        this.content = content;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
